// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/remote-host-users": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Authorize a user to access a remote host",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "remote-host-users"
                ],
                "summary": "Authorize a user to access a remote host",
                "parameters": [
                    {
                        "description": "Remote host ip",
                        "name": "remote_host",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/remotehostsapi.RemoteHostReq"
                        }
                    },
                    {
                        "description": "Username",
                        "name": "username",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/remotehostusersapi.RemoteHostUsersReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/remotehostusersapi.RemoteHostUsersResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                }
            },
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Check if a user is authorized to access a remote host if username is provided, otherwise get all users for a remote host",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "remote-host-users"
                ],
                "summary": "Check if a user is authorized to access a remote host if username is provided, otherwise get all users for a remote host",
                "parameters": [
                    {
                        "description": "Remote host ip",
                        "name": "remote_host",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/remotehostsapi.RemoteHostReq"
                        }
                    },
                    {
                        "description": "Username",
                        "name": "username",
                        "in": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/remotehostusersapi.RemoteHostUsersReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/remotehostusersapi.RemoteHostUsersResp"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Delete a user from a remote host",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "remote-host-users"
                ],
                "summary": "Delete a user from a remote host",
                "parameters": [
                    {
                        "description": "Remote host ip",
                        "name": "remote_host",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/remotehostsapi.RemoteHostReq"
                        }
                    },
                    {
                        "description": "Username",
                        "name": "username",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/remotehostusersapi.RemoteHostUsersReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "DELETED",
                    }
                }
            }
        },
        "/v1/remote-hosts": {
            "security": [
                {
                    "JWT": []
                }
            ],
            "post": {
                "description": " Create a remote host",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "remote-hosts"
                ],
                "summary": " Create a remote host",
                "parameters": [
                    {
                        "description": " Create a remote host",
                        "name": "remote_host",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/remotehostsapi.RemoteHostReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/remotehostsapi.RemoteHostReq"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                }
            },
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": " Get the remote hosts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "remote-hosts"
                ],
                "summary": " Get the remote hosts",
                "parameters": [
                    {
                        "description": " Get the remote host",
                        "name": "remote_host",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/remotehostsapi.RemoteHostReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/remotehostsapi.RemoteHostReq"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": " Delete a remote host",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "remote-hosts"
                ],
                "summary": " Delete a remote host",
                "parameters": [
                    {
                        "description": " Delete a remote host",
                        "name": "remote_host",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/remotehostsapi.RemoteHostReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "DELETED",
                    }
                }
            }
        },
        "/v1/admin/signin": {
            "post": {
                "description": "Signin an admin passing username and password in json",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Signin an admin",
                "parameters": [
                    {
                        "description": "Signin admin",
                        "name": "admin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/adminapi.AdminReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/adminapi.AdminResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/v1/logs": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "parameters": [
                    {
                        "type": "string",
                        "format": "string",
                        "description": "The ip address of the caller;The identity of the caller; The HTTP method called; The route requested; The command inserted",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "description": "Returns the logs requested; if the parameters are empty returns all",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "List logs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/log.Log"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Insert a log",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Insert a log",
                "parameters": [
                    {
                        "description": "Insert a log",
                        "name": "log",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/logapi.LogRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                }
            }
        },
        "/v1/users": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Delete user passing username",
                "tags": [
                    "users"
                ],
                "summary": "Delete an user",
                "parameters": [
                    {
                        "type": "string",
                        "format": "string",
                        "description": "user to search by username",
                        "name": "username",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "DELETED"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            },
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get user passing username",
                "tags": [
                    "users"
                ],
                "summary": "Get an user",
                "parameters": [
                    {
                        "type": "string",
                        "format": "string",
                        "description": "user to search by username",
                        "name": "username",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userapi.UserResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Signup an user passing username and password in json",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Signup an user",
                "parameters": [
                    {
                        "description": "Add user",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userapi.UserReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/userapi.UserResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Update an user passing username and password in json",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update an user",
                "parameters": [
                    {
                        "description": "Update user",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userapi.UserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userapi.UserResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/v1/users/signin": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Signin an user passing username and password in json",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Signin an user",
                "parameters": [
                    {
                        "description": "Signin user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userapi.UserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userapi.UserResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        }
    },
    "definitions": {
        "adminapi.AdminReq": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "adminapi.AdminResp": {
            "type": "object",
            "properties": {
                "jwt": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
                },
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "log.Log": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string",
                    "example": "Signin User"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "ip": {
                    "type": "string",
                    "example": "127.0.0.1:50336"
                },
                "time": {
                    "type": "string",
                    "example": "2022-10-27 10:18:47.791249"
                }
            }
        },
        "logapi.LogRequest": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string",
                    "example": "echo hello"
                },
                "ssh_address": {
                    "type": "string",
                    "example": "192.168.1.21"
                },
                "username": {
                    "type": "string",
                    "example": "user"
                }
            }
        },
        "userapi.UserReq": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "username": {
                    "type": "string",
                    "example": "user"
                }
            }
        },
        "userapi.UserResp": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "username": {
                    "type": "string",
                    "example": "user"
                }
            }
        },
        "remotehostsapi.RemoteHostReq": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string",
                    "example": "192.176.2.44"
                },
            }
        },
        "remotehostusersapi.RemoteHostUsersReq": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string",
                    "example": "elliot"
                },
            }
        },
        "remotehostusersapi.RemoteHostUsersResp": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string",
                    "example": "192.168.1.22"
                },
                "username": {
                    "type": "string",
                    "example": "elliot"
                },
            }
        },
    },
    "securityDefinitions": {
        "JWT": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:19090",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Swagger Vault support API",
	Description:      "This is an API Vault server support.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
