version: '3.9'
services:
  vault-server:
    container_name: vault-server
    tty: true
    build: ./vault
    ports:
      - 8200:8200
    restart: on-failure
    networks:
      vault-network:
        ipv4_address: 172.21.0.10
        aliases:
          - vault-server

  api-server:
    container_name: api-server
    tty: true
    build: ./api
    ports:
      - 19090:19090
    restart: on-failure
    networks:
      vault-network:
        ipv4_address: 172.21.0.30
        aliases:
          - api-server

  vault-operator:
    container_name: vault-operator
    build: ./vault-operator
    environment:
      VAULT_ADDR: "http://vault-server:8200"
    networks:
      vault-network:
        ipv4_address: 172.21.0.20
        aliases:
          - vault-operator

  postgresdb:
    build: ./db
    container_name: postgres-db
    ports:
      - '5432:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      vault-network:
        ipv4_address: 172.21.0.50
        aliases:
          - postgres-db 
volumes:
  pg_data:

networks:
  vault-network:
    ipam:
      config:
        - subnet: 172.21.0.0/24