version: '3.9'
services:
  postgres-db:
    build: ./db
    container_name: postgres-db
    ports:
      - '5432:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  vault-server:
    container_name: vault-server
    tty: true
    build: ./vault
    ports:
      - 8200:8200
    restart: on-failure

  vault-operator:
    container_name: vault-operator
    build: ./vault-operator
    environment:
      VAULT_ADDR: "http://vault-server:8200"
    depends_on:
      - vault-server

  api-server:
    container_name: api-server
    tty: true
    build: ./api
    ports:
      - 19090:19090
    restart: on-failure
    depends_on:
      vault-operator:
        condition: service_completed_successfully

  bastion-host:
    container_name: bastion-host
    tty: true
    build: ./sshwifty
    ports:
      - 8182:8182
    restart: on-failure
    depends_on:
      - api-server

  ssh-host:
    container_name: ssh-host
    tty: true
    build: ./host
    restart: on-failure
    ports:
      - 22:22
    depends_on:
      - bastion-host

  elasticsearch:
    container_name: elasticsearch
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.5.3'
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "xpack.security.transport.ssl.enabled=false"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
    expose:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    container_name: logstash
    build: ./logstash
    env_file: ./logstash/.env.docker
    volumes:
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash/pipelines/:/usr/share/logstash/pipeline/
      - ./logstash/queries/:/usr/share/logstash/config/queries/
    depends_on:
      - postgres-db
      - elasticsearch

volumes:
  pg_data:
  esdata:
    driver: local
